#!/usr/bin/env bash
# Tests for scripts/render-formula.sh, run by `make script-test`.
#
# No Homebrew is needed. The rendered formula is loaded by a small Ruby
# harness that stands in for Homebrew's formula DSL: it answers `on_macos`/
# `on_linux`/`on_arm`/`on_intel` for whichever machine a case names, records
# the `url` and `sha256` that machine would get, and runs `install` against
# recording stand-ins for `bin.install` and friends. That checks the formula
# is Ruby that loads and that each machine is handed the right tarball and
# digest — the two ways a formula breaks for one platform while looking fine
# on the others. Ruby ships with macOS and GitHub's Ubuntu runners; where it
# is missing, those checks are skipped and said to be.
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
script="$here/../render-formula.sh"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

sums="$work/sums"
mkdir -p "$sums"
# One recognisable digest per target, laid out as release.yml writes them.
write_sum() { printf '%s  eks-%s.tar.gz\n' "$(printf "$2%.0s" $(seq 64))" "$1" > "$sums/eks-$1.tar.gz.sha256"; }
write_sum aarch64-apple-darwin a
write_sum x86_64-apple-darwin b
write_sum aarch64-unknown-linux-gnu c
write_sum x86_64-unknown-linux-musl d
# Published but not a formula target: it must not be picked up.
write_sum x86_64-unknown-linux-gnu e

cat > "$work/harness.rb" <<'RUBY'
# Usage: ruby harness.rb FORMULA mac|linux arm|intel
formula, os, arch = ARGV

module Utils
  def self.safe_popen_read(*args) = "popen #{args.join(' ')}"
end

class Recorder
  def initialize(name, log) = (@name, @log = name, log)
  def install(*args) = @log << "#{@name}.install #{args.join(' ')}"
  def /(other) = Recorder.new("#{@name}/#{other}", @log)
  def write(text) = @log << "#{@name}.write #{text}"
  def to_s = @name
end

class Formula
  class << self
    attr_reader :picked_url, :picked_sha256
    def desc(_) = nil
    def homepage(_) = nil
    def license(_) = nil
    def version(v = nil) = v ? (@version = v) : @version
    def on_macos = (yield if $os == "mac")
    def on_linux = (yield if $os == "linux")
    def on_arm = (yield if $arch == "arm")
    def on_intel = (yield if $arch == "intel")
    def url(u) = (@picked_url = u)
    def sha256(s) = (@picked_sha256 = s)
    def test(&block) = (@test = block)
  end

  attr_reader :log
  def initialize = (@log = [])
  def bin = Recorder.new("bin", @log)
  def man1 = Recorder.new("man1", @log)
  def generate_completions_from_executable(*args) = @log << "completions #{args.join(' ')}"
end

$os, $arch = os, arch
load formula
puts "version #{Eks.version}"
puts "url #{Eks.picked_url}"
puts "sha256 #{Eks.picked_sha256}"
f = Eks.new
f.install
f.log.each { |line| puts line }
RUBY

failures=0
pass() { echo "ok   $1"; }
fail() {
  echo "FAIL $1" >&2
  while IFS= read -r line; do echo "     $line" >&2; done <<<"$output"
  failures=$((failures + 1))
}

run() {
  set +e
  output="$("$script" "$@" 2>&1)"
  status=$?
  set -e
}

expect_status() {
  local name="$1" want="$2"
  if [ "$status" -eq "$want" ]; then pass "$name"; else
    fail "$name: exit $status, wanted $want"; fi
}

expect_output() {
  local name="$1" needle="$2"
  if grep -qF -- "$needle" <<<"$output"; then pass "$name"; else
    fail "$name: output lacks '$needle'"; fi
}

refute_output() {
  local name="$1" needle="$2"
  if grep -qF -- "$needle" <<<"$output"; then
    fail "$name: output unexpectedly has '$needle'"
  else pass "$name"; fi
}

digest_of() { printf "$1%.0s" $(seq 64); }

# --- The acceptance case: a formula for a release, from its checksums.

run 0.2.0 "$sums"
expect_status "a_release_with_every_checksum_renders" 0
expect_output "the_formula_is_the_eks_class" "class Eks < Formula"
expect_output "the_formula_carries_the_version" 'version "0.2.0"'
expect_output "the_formula_says_it_is_generated" "Generated by scripts/render-formula.sh for v0.2.0"
expect_output "the_formula_says_how_to_tap_it_by_url" "brew tap nmcginn/eks-wrangler https://github.com/nmcginn/eks-wrangler"
refute_output "a_published_target_the_formula_does_not_use_is_left_out" "$(digest_of e)"
formula="$output"
printf '%s\n' "$formula" > "$work/eks.rb"

run v0.2.0 "$sums"
expect_status "a_leading_v_is_accepted" 0
if [ "$output" = "$formula" ]; then pass "a_leading_v_renders_the_same_formula"; else
  fail "a_leading_v_renders_the_same_formula"; fi

run 0.2.0-rc.1 "$sums"
expect_status "a_prerelease_version_renders" 0
expect_output "a_prerelease_reads_its_own_tag" "releases/download/v0.2.0-rc.1/"

# --- Each machine gets its own tarball and digest.

if command -v ruby > /dev/null 2>&1; then
  harness() {
    set +e
    output="$(ruby "$work/harness.rb" "$work/eks.rb" "$1" "$2" 2>&1)"
    status=$?
    set -e
  }
  release="https://github.com/nmcginn/eks-wrangler/releases/download/v0.2.0"

  harness mac arm
  expect_status "the_formula_loads_as_ruby" 0
  expect_output "apple_silicon_gets_the_aarch64_darwin_tarball" "url $release/eks-aarch64-apple-darwin.tar.gz"
  expect_output "apple_silicon_gets_its_digest" "sha256 $(digest_of a)"
  expect_output "the_formula_reports_its_version" "version 0.2.0"

  harness mac intel
  expect_output "an_intel_mac_gets_the_x86_64_darwin_tarball" "url $release/eks-x86_64-apple-darwin.tar.gz"
  expect_output "an_intel_mac_gets_its_digest" "sha256 $(digest_of b)"

  harness linux arm
  expect_output "aarch64_linux_gets_the_gnu_tarball" "url $release/eks-aarch64-unknown-linux-gnu.tar.gz"
  expect_output "aarch64_linux_gets_its_digest" "sha256 $(digest_of c)"

  harness linux intel
  expect_output "x86_64_linux_gets_the_static_musl_tarball_as_install_sh_does" "url $release/eks-x86_64-unknown-linux-musl.tar.gz"
  expect_output "x86_64_linux_gets_its_digest" "sha256 $(digest_of d)"

  expect_output "install_puts_the_binary_in_bin" "bin.install eks"
  expect_output "install_renders_completions_from_the_binary" "completions bin/eks completions"
  expect_output "install_renders_the_man_page_from_the_binary" "man1/eks.1.write popen bin/eks man"
else
  echo "skip the formula's Ruby checks: ruby is not installed"
fi

# --- Every digest must be present and real, or nothing is rendered.

mv "$sums/eks-x86_64-apple-darwin.tar.gz.sha256" "$work/held"
run 0.2.0 "$sums"
expect_status "a_missing_checksum_fails" 1
expect_output "a_missing_checksum_is_named" "eks-x86_64-apple-darwin.tar.gz.sha256 is missing"
refute_output "a_missing_checksum_prints_no_partial_formula" "class Eks"
mv "$work/held" "$sums/eks-x86_64-apple-darwin.tar.gz.sha256"

echo "not a digest" > "$sums/eks-aarch64-unknown-linux-gnu.tar.gz.sha256"
run 0.2.0 "$sums"
expect_status "a_checksum_file_without_a_digest_fails" 1
expect_output "a_bad_checksum_file_is_named" "eks-aarch64-unknown-linux-gnu.tar.gz.sha256 does not hold a SHA-256 digest"
write_sum aarch64-unknown-linux-gnu c

printf '%s  dist/eks-aarch64-unknown-linux-gnu.tar.gz\n' "$(digest_of C)" > "$sums/eks-aarch64-unknown-linux-gnu.tar.gz.sha256"
run 0.2.0 "$sums"
expect_status "a_checksum_naming_another_directory_still_renders" 0
expect_output "an_uppercase_digest_is_written_lowercase" "sha256 \"$(digest_of c)\""
write_sum aarch64-unknown-linux-gnu c

# --- Usage.

run latest "$sums"
expect_status "a_version_that_is_not_one_is_a_usage_error" 2
expect_output "a_bad_version_says_what_a_good_one_looks_like" "pass one like 0.2.0"

run 0.2 "$sums"
expect_status "a_two_part_version_is_a_usage_error" 2

run 0.2.0 "$work/nowhere"
expect_status "a_missing_directory_is_a_usage_error" 2
expect_output "a_missing_directory_says_what_to_put_there" "download the release's .sha256 files"

run 0.2.0
expect_status "a_missing_argument_is_a_usage_error" 2

if [ "$failures" -ne 0 ]; then
  echo "$failures render-formula test(s) failed" >&2
  exit 1
fi
echo "render-formula: all tests passed"
