#!/usr/bin/env bash
# Print the Homebrew formula for release $1 (e.g. 0.2.0), reading each
# tarball's digest from the `eks-<target>.tar.gz.sha256` files in $2.
#
# release.yml runs this on a `v*` tag, over the checksums it has just
# published, and commits the result as Formula/eks.rb (decision 119). The
# formula is generated rather than edited because four digests have to change
# together on every release, and a hand edit that updates three of them is a
# formula that fails `brew install` on the fourth platform only.
set -euo pipefail

if [ "$#" -ne 2 ]; then
  echo "usage: $0 <version> <checksum-dir>" >&2
  exit 2
fi

version="${1#v}"
dir="$2"

if ! [[ "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+([-+][0-9A-Za-z.-]+)?$ ]]; then
  echo "render-formula: '$1' is not a release version — pass one like 0.2.0" >&2
  exit 2
fi
if [ ! -d "$dir" ]; then
  echo "render-formula: $dir is not a directory — download the release's .sha256 files into one first" >&2
  exit 2
fi

# The four builds Homebrew can install: both macOS architectures, and on
# Linux the same choice install.sh makes — the static musl build for x86_64,
# the only build there is for aarch64.
digest() {
  local file="$dir/eks-$1.tar.gz.sha256"
  if [ ! -f "$file" ]; then
    echo "render-formula: $file is missing — every target the formula names needs its published checksum" >&2
    exit 1
  fi
  local sum
  sum="$(cut -d ' ' -f 1 < "$file" | head -n 1 | tr 'A-F' 'a-f')"
  if ! [[ "$sum" =~ ^[0-9a-f]{64}$ ]]; then
    echo "render-formula: $file does not hold a SHA-256 digest" >&2
    exit 1
  fi
  echo "$sum"
}

mac_arm="$(digest aarch64-apple-darwin)"
mac_intel="$(digest x86_64-apple-darwin)"
linux_arm="$(digest aarch64-unknown-linux-gnu)"
linux_intel="$(digest x86_64-unknown-linux-musl)"

url="https://github.com/nmcginn/eks-wrangler/releases/download/v$version"

cat <<EOF
# Generated by scripts/render-formula.sh for v$version — do not edit by hand.
# Install with:
#   brew tap nmcginn/eks-wrangler https://github.com/nmcginn/eks-wrangler
#   brew install nmcginn/eks-wrangler/eks
class Eks < Formula
  desc "Fast, keyboard-driven explorer for AWS EKS clusters"
  homepage "https://github.com/nmcginn/eks-wrangler"
  version "$version"
  license "MIT"

  on_macos do
    on_arm do
      url "$url/eks-aarch64-apple-darwin.tar.gz"
      sha256 "$mac_arm"
    end
    on_intel do
      url "$url/eks-x86_64-apple-darwin.tar.gz"
      sha256 "$mac_intel"
    end
  end

  on_linux do
    on_arm do
      url "$url/eks-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "$linux_arm"
    end
    on_intel do
      url "$url/eks-x86_64-unknown-linux-musl.tar.gz"
      sha256 "$linux_intel"
    end
  end

  def install
    bin.install "eks"
    # Rendered by the installed binary rather than copied from the tarball,
    # because the x86_64-apple-darwin tarball is built without them.
    generate_completions_from_executable(bin/"eks", "completions")
    (man1/"eks.1").write Utils.safe_popen_read(bin/"eks", "man")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/eks --version")
  end
end
EOF
